sudo: required

services:
  - docker

env:
  - TEST_SLEEPS="0.7"

# Note: When I try to map ports `-p ${SELENIUM_HUB_PORT}:${SELENIUM_HUB_PORT}`
#   I get Error response from daemon: Cannot start container 9da9d7a1176:
#   failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0
#   -p tcp -d 172.17.0.1 --dport 24444 -j ACCEPT:
#   iptables: No chain/target/match by that name. (exit status 1)
before_install:
  - ./host-scripts/gen-scm-source.sh
  - docker build -t selenium .

install:
  - docker run --name=grid -d -e VIDEO=true -v /dev/shm:/dev/shm selenium
  - docker exec -ti grid wait_all_done 40s
  - docker exec grid versions
  - docker exec grid errors || true
  - docker logs grid

# Note: If we try to use `--net` Travis fails with System error: permission denied
# Note: If we try to use `--link` Selenium fails with ConnectionRefusedError after
#  connect to selenium at http://172.17.0.4:24444/wd/hub
# Unless, we use `--privileged` trick by Hiro Asari from Travis Corp.
script:
  - docker exec -ti grid test
  - docker cp grid:/test/console.png images/grid_console.png

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - docker exec grid stop || true
  - docker stop grid || true
  - docker rm grid || true
