# Even though we run everything inside docker Travis require
# us to pick a language else it will pick Ruby by default
language: generic

# Omit running tests on temporal branches,
#  i.e. branches with names that start with "tmp"
branches:
  except:
    - /^tmp/

env:
  global:
    - TEST_SLEEPS="0.7"

matrix:
  allow_failures:
    # Currently erroring in Mac (OSX):
    #  https://travis-ci.org/elgalu/docker-selenium/jobs/143553463#L636
    #   com.docker.docker Incompatible CPU detected
    #   Docker requires a processor with virtualization capabilities
    - env:
        - DOCKER_VERSION="1.12.0-rc4"
          DOCKER_COMPOSE_VERSION="1.8.0-rc2"
          OPERATING_SYSTEM="osx"
  include:
    # Linux with docker:stable compose:stable
    - os: linux
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.7.1"
          DOCKER_PUSH=true
    # Linux with docker:beta compose:stable
    - os: linux
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.0-rc4"
          DOCKER_COMPOSE_VERSION="1.7.1"
    # Linux with docker:stable compose:beta
    - os: linux
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.8.0-rc2"
    # Linux with docker:beta compose:beta
    - os: linux
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.0-rc4"
          DOCKER_COMPOSE_VERSION="1.8.0-rc2"
    # Mac OSX: only test native docker version
    - os: osx
      osx_image: xcode8
      env:
        - DOCKER_VERSION="1.12.0-rc4"
          DOCKER_COMPOSE_VERSION="1.8.0-rc2"
          OPERATING_SYSTEM="osx"

before_install:
  - travis_retry ./test/before_install_setup
  - travis_retry ./test/before_install_build

install:
  - ./test/install

script:
  - ./test/script_start
  - travis_retry ./test/script_scenario_make
  # - travis_retry ./test/script_scenario_compose_1_1
  # - travis_retry ./test/script_scenario_compose_N_N
  - ./test/script_end

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - ./test/after_script
