sudo: required

services:
  - docker

# Even though we run everything inside docker Travis require
# us to pick a language else it will pick Ruby by default
language: python
python:
  - "2.7"

env:
  - TEST_SLEEPS="0.7"

before_install:
  - travis_retry ./test/before_install_setup
  - travis_retry ./test/before_install_build

install:
  - ./test/install

script:
  - travis_retry ./test/script_scenario_1
  - ./test/script_scenario_2
  - ./test/script_archive
  - ./test/script_push

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - ./test/after_script
