version: '2'

services:
  hub:
    image: elgalu/selenium
    ports:
      - ${SELENIUM_HUB_PORT}:${SELENIUM_HUB_PORT}
    environment:
      - SELENIUM_HUB_PORT
      - VNC_START=false
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium
    network_mode: "service:hub"
    shm_size: 1g
    environment:
      - SELENIUM_HUB_PORT
      - VNC_START=false
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=false
      - CHROME=true
      - FIREFOX=false

  firefox:
    image: elgalu/selenium
    network_mode: "service:hub"
    environment:
      - SELENIUM_HUB_PORT
      - VNC_START=false
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=false
      - CHROME=false
      - FIREFOX=true

#-- Notes --#
# shm_size: 1g
#  Fixes small 64 mb /dev/shm inside docker containers
#   see: https://github.com/docker/compose/blob/1.7.1/compose/config/config.py#L79
#  Can also be fixed with:
#   volumes:
#     - /dev/shm:/dev/shm
#  Can also be fixed with:
#   environment:
#     - SHM_TRY_MOUNT_UNMOUNT=true
