version: '2'
# wget -nv https://git.io/vKiKx -O docker-compose.yml
services:
  hub:
    image: elgalu/selenium
    environment:
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium
    shm_size: 1g
    environment:
      - GRID=false
      - CHROME=true
      - FIREFOX=false

  firefox:
    image: elgalu/selenium
    environment:
      - GRID=false
      - CHROME=false
      - FIREFOX=true
